### PR TITLE
Allow VC_API_TOKEN passing via ENV Variable instead of Build Arg

### PR DESCRIPTION
**Pull request by BastianM3**
- Split the build process so that VC_API_TOKEN can be passed in at runtime, rather than at build time.
    - Migrated entrypoint to a shell script in order to accomplish the above.

### CODE REVIEW

**Comment by BastianM3** [comment]
Ok - I just made some changes. Might be best to migrate this Dockerfile and shell script to a separate folder if case you'd like for users to still be able to bake the token into the image 👍

**Comment by gkristic-vc** [comment]
I'm just finding that my line comment didn't get through, for some reason! 😮  When I said "I still had a minor comment on the quoting..." I was talking about a comment I made on [this](https://github.com/VividCortex/docker/blob/32e0a269b07b206670efafc7c905bff8cc9543ed/alpine/run.sh#L17) line, that should be using a quoted `"$@"` instead, to correctly cope with spaces that could potentially be provided in arguments. Other than that, this is good to merge IMO.

**Comment by gkristic-vc** [comment]
Sorry about the missing comment. I have no idea why it didn't make it with the review. Thanks for your time Marcus!

**Comment by efepapa** [comment]
Hey @BastianM3,
There's a not-yet-documented install option that may be handy: if you use `NO` as token, the installer won't write an `api-token` to `global.conf` -> the agents will require a `VC_API_TOKEN` environment variable instead.

**Comment by gkristic-vc** [comment]
Honestly, I think that we should use that, so that we don't need to defer the install to run time. We could keep it where it was, during container build. If the token is provided, then we use it for the install and thus keep it in the image, as we were doing before. If not, we proceed to install without a token using the `NO` argument that Fernando pointed out. In that case the token must provided at run time.

**Comment by BastianM3** [comment]
Oh, that's good to know! In that case, I guess we don't even need this PR then 🤔

**Comment by gkristic-vc** [comment]
Mostly not... I'd still argue that people don't necessarily know the `NO` trick, so I'd still keep the Dockerfile aware and insert the `NO` when no token is provided.

**Pull request closed without merging**
